### ISSUE TITLE
Run server-side blazor on full framework (net461)

### ISSUE THREAD

**Issue by chris-ray** [aspnet/Blazor#1202]
Currently we can run ASP.NET Core 2 apps targeting the full framework. This allows me to wrap up some of my legacy code that has full-framework dependencies and put a nice ASP.NET Core 2 web api around it.

It would be great if Server-Side blazor was allowed to run on full framework for the same reason. Are there any specific impediments to supporting this?

**Comment by danroth27** [comment]
I gave it a shot. I took the server-side template and update the csproj file like this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <DebugType>full</DebugType>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Server" Version="0.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApplication8.App\WebApplication8.App.csproj" />
  </ItemGroup>

</Project>
```

I get this exception at runtime:

```
System.InvalidOperationException: The following routes are ambiguous:
'fetchdata' in 'WebApplication8.App.Pages.FetchData'
'fetchdata' in 'WebApplication8.App.Pages.FetchData'

   at Microsoft.AspNetCore.Blazor.Routing.RouteTable.RouteComparison(RouteEntry x, RouteEntry y)
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Blazor.Routing.RouteTable.Create(IEnumerable`1 types)
   at Microsoft.AspNetCore.Blazor.Routing.Router.SetParameters(ParameterCollection parameters)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.StateHasChanged()
   at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters(ParameterCollection parameters)
   at Microsoft.AspNetCore.Blazor.Browser.Rendering.RemoteRenderer.AddComponent(Type componentType, String domElementSelector)
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitHost.<InitializeAsync>b__34_0()
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitSynchronizationContext.<>c__DisplayClass8_0.<Invoke>b__0(Object _)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitHost.<InitializeAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Blazor.Server.Circuits.BlazorHub.<StartCircuit>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<ExecuteHubMethod>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>d__13.MoveNext()
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'BeginInvokeDotNetFromJS'.
System.InvalidOperationException: The CircuitHost is null. This is due to an exception thrown during initialization.
   at Microsoft.AspNetCore.Blazor.Server.Circuits.BlazorHub.EnsureCircuitHost()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<ExecuteHubMethod>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>d__13.MoveNext()
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'BeginInvokeDotNetFromJS'.
System.InvalidOperationException: The CircuitHost is null. This is due to an exception thrown during initialization.
   at Microsoft.AspNetCore.Blazor.Server.Circuits.BlazorHub.EnsureCircuitHost()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<ExecuteHubMethod>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>d__13.MoveNext()
```

**Comment by chris-ray** [comment]
I did not try but I will pick up where dan left off tomorrow, thanks.

**Comment by chris-ray** [comment]
@danroth27 that is same error as #1151

**Comment by wanton7** [comment]
Should this be closed because ASP.NET Core 3.0 is no longer going to support full framework?

**Comment by danroth27** [comment]
Yes, I believe so.

**Comment by chris-ray** [comment]
Ouch, this kills my plans of a path-forward for writing a blazor UI layer over an old wpf app with full-framework dependencies.

**Comment by SteveSandersonMS** [comment]
Sorry @chris-ray! It's the result of a bigger set of changes for .NET as a whole.
