### ISSUE TITLE
Components (Pages) randomly not building in 0.5.0

### ISSUE THREAD

**Issue by chanan** [aspnet/Blazor#1206]
Not sure if I can reproduce this in a smaller project.

I have a project: https://github.com/chanan/BlazorStrap that is a Blazor library plus a site the uses that library. The project was upgraded from 0.3.0 -> 0.5.0 (Skipped of 0.4.0 due to a blocking bug in 0.4.0). After upgrading both projects, I did a clean and then a build from within Visual Studio. I started checking the site and I noticed that many Components that have routes give me this error:

```
blazor.webassembly.js:1 Uncaught (in promise) Error: System.InvalidOperationException: 'Router' cannot find any component with a route for '/alerts2'.
  at Microsoft.AspNetCore.Blazor.Routing.Router.Refresh () <0x1c7cb70 + 0x000b4> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Routing.Router.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x1be5e90 + 0x0003e> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1b6cfb0 + 0x00082> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1b6ce20 + 0x0008a> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InsertNewFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 newFrameIndex) <0x1b6cb00 + 0x000ca> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 oldStartIndex, System.Int32 oldEndIndexExcl, System.Int32 newStartIndex, System.Int32 newEndIndexExcl) <0x1b6c298 + 0x0024a> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff (Microsoft.AspNetCore.Blazor.Rendering.Renderer renderer, Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange`1[T] oldTree, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange`1[T] newTree) <0x1b65ea8 + 0x000a6> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1b63350 + 0x000b8> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderQueueEntry renderQueueEntry) <0x1b62f78 + 0x00040> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue () <0x1b62718 + 0x00048> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue (System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1b54240 + 0x0006e> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Components.RenderHandle.Render (Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1b53f28 + 0x0003a> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.StateHasChanged () <0x1b53e30 + 0x00048> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x1b47360 + 0x000e0> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent (System.Type componentType, System.String domElementSelector) <0x1aef5d0 + 0x00090> in <7f8d33166e1d4772b374a06ec932c48c>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyBlazorApplicationBuilder.CreateRenderer () <0x1ad10d0 + 0x00078> in <7f8d33166e1d4772b374a06ec932c48c>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsync (System.Threading.CancellationToken cancellationToken) <0x1ab57c8 + 0x0010c> in <7f8d33166e1d4772b374a06ec932c48c>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostExtensions.Run (Microsoft.AspNetCore.Blazor.Hosting.IWebAssemblyHost host) <0x1ab4f48 + 0x00020> in <7f8d33166e1d4772b374a06ec932c48c>:0 
  at Sample.Program.Main (System.String[] args) [0x00001] in C:\Users\cbraunstein\source\repos\BlazorStrap\src\Sample\Program.cs:9 
  at Microsoft.AspNetCore.Blazor.Routing.Router.Refresh () <0x1c7cb70 + 0x000b4> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Routing.Router.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x1be5e90 + 0x0003e> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1b6cfb0 + 0x00082> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1b6ce20 + 0x0008a> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InsertNewFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 newFrameIndex) <0x1b6cb00 + 0x000ca> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 oldStartIndex, System.Int32 oldEndIndexExcl, System.Int32 newStartIndex, System.Int32 newEndIndexExcl) <0x1b6c298 + 0x0024a> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff (Microsoft.AspNetCore.Blazor.Rendering.Renderer renderer, Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange`1[T] oldTree, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange`1[T] newTree) <0x1b65ea8 + 0x000a6> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1b63350 + 0x000b8> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderQueueEntry renderQueueEntry) <0x1b62f78 + 0x00040> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue () <0x1b62718 + 0x00048> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue (System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1b54240 + 0x0006e> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Components.RenderHandle.Render (Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1b53f28 + 0x0003a> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.StateHasChanged () <0x1b53e30 + 0x00048> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x1b47360 + 0x000e0> in <14b3737636c3454d9ebdd58807bbf070>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent (System.Type componentType, System.String domElementSelector) <0x1aef5d0 + 0x00090> in <7f8d33166e1d4772b374a06ec932c48c>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyBlazorApplicationBuilder.CreateRenderer () <0x1ad10d0 + 0x00078> in <7f8d33166e1d4772b374a06ec932c48c>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHost.StartAsync (System.Threading.CancellationToken cancellationToken) <0x1ab57c8 + 0x0010c> in <7f8d33166e1d4772b374a06ec932c48c>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostExtensions.Run (Microsoft.AspNetCore.Blazor.Hosting.IWebAssemblyHost host) <0x1ab4f48 + 0x00020> in <7f8d33166e1d4772b374a06ec932c48c>:0 
  at Sample.Program.Main (System.String[] args) [0x00001] in C:\Users\cbraunstein\source\repos\BlazorStrap\src\Sample\Program.cs:9 
    at Object.callMethod (blazor.webassembly.js:1)
    at Object.callEntryPoint (blazor.webassembly.js:1)
    at blazor.webassembly.js:1
    at blazor.webassembly.js:1
    at Object.next (blazor.webassembly.js:1)
    at i (blazor.webassembly.js:1)
callMethod @ blazor.webassembly.js:1
callEntryPoint @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
l @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
l @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
l @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
``` 

You will note that the route is /alerts2 - that is due to try to change the route from /alerts to a different route and see if it worked. It didnt.

Looking in the obj folder I see the Pages folder but the Alerts.g.i.cs and Alerts.g.cs are missing (as well as some others, but some are there). 

I removed everything from Alerts.cshtml so it now looks like so:

```
@page "/alerts2"

<h1>Alerts</h1>
```

The build output shows no error.

However curiously, the error list does show:

```
Error	fatal-error	(ESLint) ESLint encountered a parsing error.	Sample JavaScript Content Files	C:\Users\cbraunstein\source\repos\BlazorStrap\src\Sample\Pages\Alerts.cshtml	1	Active
```

Which makes no sense since I don't have anything that file at the moment.

No sure how I can get a reproduction sample other than I can upload to my repo the current state of BlazorStrap

**Comment by chanan** [comment]
Blazor 0.5.1 did not fix this issue.

**Comment by rynowak** [comment]
What does your project file look like?

**Comment by Suchiman** [comment]
Try changing your csproj to
```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Browser" Version="0.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.5.1" />
    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.5.1" />
  </ItemGroup>

</Project>
```
and try again

**Comment by chanan** [comment]
I am now getting another weird error on build:

```
Error		rzc generate exited with code 1.	Sample	C:\Users\cbraunstein\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\RazorCompilation.targets	184	
```

Which leads to this line:

```
<RazorGenerate
      Debug="$(_RazorDebugGenerateCodeTask)"
      DebugTool="$(_RazorDebugGenerateCodeTool)"
      ToolAssembly="$(_RazorToolAssembly)"
      UseServer="$(UseRazorBuildServer)"
      ForceServer="$(_RazorForceBuildServer)"
      PipeName="$(_RazorBuildServerPipeName)"
      Version="$(RazorLangVersion)"
      Configuration="@(_BlazorDeclarationConfiguration)"
      Extensions="@(RazorExtension)"
      Sources="@(_BlazorGenerateDeclarationWithTargetPath)"
      ProjectRoot="$(MSBuildProjectDirectory)"
      TagHelperManifest="$(_BlazorGenerateDeclarationComponentManifest)" />
```

**Comment by MarkStega** [comment]
@chanan 
I didn't see this when I posted #1231; I wanted to use BlazorStrap and saw that it hadn't been updated to 0.5.1 so I forked the repo and cloned it with the intention of making the updates and submitting a PR.

I ran into the identical issue of not having all pages built. I went into the csproj and found the same weirdness, When I remove the lines (getting the csproj down to what is suggested above by @Suchiman I get the same error.

```
1>------ Build started: Project: Sample, Configuration: Debug Any CPU ------
1>One or more errors occurred. (Stack empty.)
1>   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
1>   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
1>--- End of stack trace from previous location where exception was thrown ---
1>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
1>   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
1>   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
1>   at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.GenerateCode(RazorProjectEngine engine, SourceItem[] inputs)
1>   at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.ExecuteCore(RazorConfiguration configuration, String projectDirectory, String tagHelperManifest, List`1 sources, List`1 outputs, List`1 relativePaths)
1>   at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.ExecuteCoreAsync()
1>   at Microsoft.AspNetCore.Razor.Tools.CommandBase.<ExecuteAsync>d__13.MoveNext()
1>C:\Users\ms\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.1\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code 1.
1>Done building project "Sample.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by chanan** [comment]
Thanks Mark for taking a look, I didnt see anything special about this project that should cause this, did you?

**Comment by danroth27** [comment]
@pranavkm @rynowak I was able to reproduce this as well. Repro here: https://github.com/danroth27/BlazorStrap/tree/danroth27/0.5.1

**Comment by danroth27** [comment]
MSBuild log: [msbuild.log](https://github.com/aspnet/Blazor/files/2243148/msbuild.log)

**Comment by MarkStega** [comment]
@chanan No, nothing other than the odd "<none include" statements and the "removes"; At least @danroth27  reproduced this so I am presuming it is in the hands of Team Blazor.

**Comment by pranavkm** [comment]
Filed an issue for rzc.dll to better print the actual stack trace - https://github.com/aspnet/Razor/issues/2519. 

The actual exception is thrown from here - https://github.com/aspnet/Blazor/blob/2975ebb99991a4566f2a92f4de69fe55c3e948a2/src/Microsoft.AspNetCore.Blazor.Razor.Extensions/ComponentDocumentRewritePass.cs#L215-L223. The issue here is `col` is [void element](https://github.com/aspnet/Blazor/blob/2975ebb99991a4566f2a92f4de69fe55c3e948a2/src/Microsoft.AspNetCore.Blazor.Razor.Extensions/ComponentDocumentRewritePass.cs#L26-L29) and gets popped here:
https://github.com/aspnet/Blazor/blob/2975ebb99991a4566f2a92f4de69fe55c3e948a2/src/Microsoft.AspNetCore.Blazor.Razor.Extensions/ComponentDocumentRewritePass.cs#L215-L219

For `EndTags`, the element is popped twice: https://github.com/aspnet/Blazor/blob/2975ebb99991a4566f2a92f4de69fe55c3e948a2/src/Microsoft.AspNetCore.Blazor.Razor.Extensions/ComponentDocumentRewritePass.cs#L223 and you get:

```C#
Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at Microsoft.AspNetCore.Blazor.Razor.ComponentDocumentRewritePass.RewriteWalker.RewriteChildren(RazorSourceDocument source, IntermediateNode node)
   at Microsoft.AspNetCore.Blazor.Razor.ComponentDocumentRewritePass.RewriteWalker.VisitDefault(IntermediateNode node)
   at Microsoft.AspNetCore.Razor.Language.Intermediate.IntermediateNodeVisitor.VisitMethodDeclaration(MethodDeclarationIntermediateNode node) in D:\work\Razor\src\Microsoft.AspNetCore.Razor.Language\Intermediate\IntermediateNodeVisitor.cs:line 79
```

That bit of code needs to be hardened

**Comment by chanan** [comment]
Renaming Col to BlazorCol fixes this issue. I forgot that html has a Col element

**Comment by pranavkm** [comment]
> I think this issue can be closed?

The code still feels incorrect. @SteveSandersonMS should be able to confirm

**Comment by chanan** [comment]
I have asked in the past if we can have tags with the same name as html elements and the answer is no.

It's true that the error message should have been better, but I don't think that should be fixed from within this ticket, but I dont know, that was the source of my question, I should have been more clear.
