### ISSUE TITLE
Question: Entityframework CRUD with Blazor Server Side

### ISSUE THREAD

**Issue by simonziegler** [aspnet/Blazor#1246]
I have an existing Client/Server Blazor project, that I have just updated to Blazor 0.5.1. The client side runs quite slow, principally due to the time taken to decode JSON (I raised a couple of issues here to see if MessagePack could be used - it cannot because .Net Standard 2.0 does not support System.Reflection.Emit).

I am keen to attempt a port to Blazor ServerSide, which clearly has substantial performance benefits. I am however using EntityFramework Core and SignalR. My question is where I should locate the EntityFramework code: in the Server or App project? So far I attempted to place it in the App, but cannot install for instance the Microsoft.AspNetCore.App Nuget package because it is incompatible with .Net Standard 2.0. Any thoughts please?

I guess that if I do need to use the Server (and I am happy to try), I will again need a Shared Project. This is not a problem because I already have one of these!

Thanks again to the Blazor team for a stunning product. Like many here I hope that Microsoft commits to it and that it can stop being "experimental"...

**Comment by danroth27** [comment]
> The client side runs quite slow, principally due to the time taken to decode JSON

Yes, this is a known issue that we are working on with the Mono folks on. @kumpera FYI.

> My question is where I should locate the EntityFramework code: in the Server or App project?

When you run Blazor server-side all of the component logic and event handling code runs on the server. This means you can reasonably connect to the DB from the Blazor server-side project, which lives in the App project. You may also want to connect to your DB from your Server project for any Razor Pages, Web APIs or MVC controllers that you have. Both the App and Server projects share the same service provider, so really either project should be fine.

> So far I attempted to place it in the App, but cannot install for instance the Microsoft.AspNetCore.App Nuget package because it is incompatible with .Net Standard 2.0.

You shouldn't need to reference Microsoft.AspNetCore.App to just use EF. Why are you trying to do this?

**Comment by simonziegler** [comment]
So I now have the following status, which qualifies as part successful!

- The SQLite database can sit on the Server (I know that this is working correctly), and uses EF, plus the various Authentication and Identity libraries (this is a web app requiring log in). HOWEVER, I cannot work out how to set up an HttpClient on the App project so that the App can query the Server project's database. I know that using Http from one part of a server to another seems odd, but since the Server project has a dependency on the App project, I cannot think of any other way to communicate between them.
- If I move the database code to the App project, I cannot resolve the Identity data type through Nuget, and so cannot access the database.

Any thoughts what I might be doing wrong? It would be great to get this working and to access the performance enhancement to be had from Blazor ServerSide.

Thanks!

**Comment by simonziegler** [comment]
Hi @danroth27, I have attempted to consume

**Comment by simonziegler** [comment]
Accidentally closed thread and reopening.

**Comment by simonziegler** [comment]
Hi @danroth27 (or whoever may have a view),

I have successfully managed to consume a small service created in the Server project from the App project. The service is represented by a common interface and does no more than return a "hello" string from a single function call.

However, the same is not true for my database handling service. This is a class in the Server project that itself consumes another Server class that is the database context (which inherits from Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext. I get the error message below, even if I install Microsoft.AspNetCore.Identity (version 2.1.0 for compatibility) in the App project beforehand. I'm rather stuck!

I guess the question is whether I am barking up the wrong tree with my approach. I would ideally move all the database work into the App project, but I suffered with referencing the relevant packages for Identity work (I do not know whether that was down my error or otherwise).

Any assistance would be appreciated - thank you.

```
System.InvalidOperationException: Cannot consume scoped service 'DioptraWebApp02ServerSide.Server.DataAccess.ApplicationDbContext' from singleton 'DioptraWebApp02ServerSide.Shared.IDevelopmentController'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScoped(ScopedCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitSingleton(SingletonCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitSingleton(SingletonCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitSingleton(SingletonCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitSingleton(SingletonCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(IServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnCreate(IServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Blazor.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>b__2(IComponent instance)
   at Microsoft.AspNetCore.Blazor.Components.ComponentFactory.PerformPropertyInjection(IComponent instance)
   at Microsoft.AspNetCore.Blazor.Components.ComponentFactory.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters(ParameterCollection parameters)
   at Microsoft.AspNetCore.Blazor.Browser.Rendering.RemoteRenderer.AddComponent(Type componentType, String domElementSelector)
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitHost.<InitializeAsync>b__34_0()
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitSynchronizationContext.<>c__DisplayClass8_0.<Invoke>b__0(Object _)
```

**Comment by simonziegler** [comment]
Thanks @SteveSandersonMS. The Auth stuff is proving very difficult, but that is mostly down to my inexperience with ASP.NET.

**Comment by simonziegler** [comment]
Actually @SteveSandersonMS, this may or may not be the correct architecture for you, however I would be able to move forward if the App Project were able to communicate with the Server project via Http. From what I can tell, the App's HttpClient is missing a BaseAddress. If this is architecturally wrong, my bad for the suggestion!

**Comment by danroth27** [comment]
@simonziegler Having the server communicate with itself over HTTP really shouldn't be necessary. Any functionality that needs to be shared could be made available as a service or other API that you can just call directly. 


That said you could configure the BaseAddress of the HttpClient using the ASP.NET Core [configuration](https://docs.microsoft.com/aspnet/core/fundamentals/configuration) API.

**Comment by moataz1991** [comment]
im facing the same thing
should App reference Server as the Server reference App for communications and services sharing ?!
is there a small example on that for auth and dbcontext ?

im having trouble understanding the logic of running blazor on the server , sry im a WPF guy :)

**Comment by moataz1991** [comment]
also sending data from client to the server-side blazor
how it is done , how to encrypt-decrypt if the whole this is running on the server ?
does this mean we dont need security tokens ? cuz obviously we dont need HttpClient and sure no more controllers too

it looks simpler yet hard to imagine the connection between server and UI (client)
