### ISSUE TITLE
Mono IL Linker Error with MVC Scaffolding

### ISSUE THREAD

**Issue by JamJar00** [aspnet/Blazor#1380]
Having added MVC scaffolding to my Blazor project Mono is unable to resolve the System.Resources.Reader assembly.
```
Fatal error in IL Linker
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Usrs\Jamie\.nuget\packages\system.resources.reader\4.3.0\lib\netstandard1.0\System.Resources.Reader.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Usrs\Jamie\.nuget\packages\system.resources.reader\4.3.0\lib\netstandard1.0\System.Resources.Reader.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(String name)
   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

Have confirmed the DLL is present and the linker is finding it (I get a different error if it's not there).

I'm not entirely sure how I got here so it's hard to reproduce. I added MVC scaffolding, resolved the errors the import brought and was able to run the project, but having added controllers and models this error is thrown every build.

The usual cleaning the project/deleting the bin and obj folders hasn't helped. Backtracking and removing the controller and model files I added also hasn't helped.

**Comment by JamJar00** [comment]
Having tried to remove all MVC code from the project it's now throwing:
```
Fatal error in IL Linker
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\Jamie\.nuget\packages\system.io.filesystem.primitives\4.3.0\lib\netstandard1.3\System.I.FileSystem.Primitives.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\Jamie\.nuget\packages\system.io.filesystem.primitives\4.3.0\lib\netstandard1.3\System.I.FileSystem.Primitives.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(String name)
   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

I'll try starting over in a new project...!

**Comment by JamJar00** [comment]
Originally the error was with Full Dependency scaffolding, just remade with Minimal Dependency scaffolding and the error is immediately present having just created a new project and added the minimal scaffolding.

**Comment by JamJar00** [comment]
That peaked my curiosity actually, forgot to mention it. The path is passed into the `dotnet` command correctly, it's somewhere in there it's getting lost.

In the second error that I got for System.IO.FileSystem.Primitives there's an 'a' missing from 'netstandard1.3' (is 'netstndard1.3' instead).

And having re-added the MVC code I'm getting this:
```
Fatal error in IL Linker
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.typeextensions\4.3.0\lib\netstandard1.5\System.Reflection.TypeExtensins.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.typeextensions\4.3.0\lib\netstandard1.5\System.Reflection.TypeExtensins.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(String name)
   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```
Note 'TypeExtensins' missing an 'o'.

As you say may be nothing, but it's very odd...

**Comment by SteveSandersonMS** [comment]
Thanks for posting.

So that we can investigate, could you re-express this bug report in the form of repro steps? Given a clean new Blazor app project, what minimal steps cause compilation to fail with this error?

Just FYI, I wouldn't expect MVC's built-in scaffolding code to produce a working result in a Blazor client app project, because MVC and Blazor are completely different app frameworks whose APIs are based around different paradigms (MVC is request-response, Blazor is stateful).

**Comment by JamJar00** [comment]
That makes sense I guess, looks like this is related to issue #996 as I was adding it to the "Blazor" template. I hadn't realised that was *only* client side.

Interestingly, but another separate issue, is that the Blazor (ASP.NET Core Hosted) template (which I presume is what I should be using) isn't being setup correctly for me and is seemingly missing most of it's files; which is why I wasn't using that template in the first place. I'll see if I can fix that or create an other issue.

It would certainly be useful to have a note on the "Blazor" template description about it being *only* client side and, as per the linked issue, you probably shouldn't be able to scaffold the MVC in!

**Comment by SteveSandersonMS** [comment]
Great, thanks for the info!
