### ISSUE TITLE
Failed in resolve dependencies After adding msgpack-cli

### ISSUE THREAD

**Issue by hungdluit90** [aspnet/Blazor#1553]
msgpack-cli currently support mono build. https://github.com/msgpack/msgpack-cli
But I got errors MSB3037 while making build.

![image](https://user-images.githubusercontent.com/40863525/46847071-b23be800-ce0c-11e8-88cf-b6eeda031b49.png)

**Comment by danroth27** [comment]
Here's what I tried:

- Created a new Blazor app
- Added the MsgPack.Cli package
- Added the following code to Program.cs:

  ```csharp
            var msgPacker = MsgPack.Serialization.MessagePackSerializer.Get<Foo>();
            var stream = new MemoryStream();
            msgPacker.Pack(stream, new Foo { Count = 1, Text = "test" });
            stream.Seek(0, SeekOrigin.Begin);
            var foo = msgPacker.Unpack(stream);
  ```

Build error:

```
Error MSB3073
The command "dotnet "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\targets\../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true
-d "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\targets\../tools/mono/bcl/" 
-d "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\targets\../tools/mono/bcl/Facades/" 
-o "C:\Users\daroth\Source\Repos\WebApplication19\WebApplication19\obj\Debug\netstandard2.0\blazor\linker/" 
-x "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\targets\BuiltInBclLinkerDescriptor.xml" 
-x "C:\Users\daroth\Source\Repos\WebApplication19\WebApplication19\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" 
-a "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor\0.6.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" 
-a "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.browser\0.6.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" 
-a "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\lib\netstandard1.0\Microsoft.AspNetCore.Blazor.TagHelperWorkaround.dll" 
-a "C:\Users\daroth\.nuget\packages\microsoft.extensions.dependencyinjection\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" 
-a "C:\Users\daroth\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" 
-a "C:\Users\daroth\.nuget\packages\microsoft.jsinterop\0.6.0\lib\netstandard2.0\Microsoft.JSInterop.dll" 
-a "C:\Users\daroth\.nuget\packages\mono.webassembly.interop\0.6.0\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" 
-a "C:\Users\daroth\.nuget\packages\msgpack.cli\1.0.0\lib\netstandard2.0\MsgPack.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.collections.concurrent\4.0.12\lib\netstandard1.3\System.Collections.Concurrent.dll" 
-a "C:\Users\daroth\.nuget\packages\system.collections.nongeneric\4.0.1\lib\netstandard1.3\System.Collections.NonGeneric.dll" 
-a "C:\Users\daroth\.nuget\packages\system.collections.specialized\4.0.1\lib\netstandard1.3\System.Collections.Specialized.dll" 
-a "C:\Users\daroth\.nuget\packages\system.data.common\4.1.0\lib\netstandard1.2\System.Data.Common.dll" 
-a "C:\Users\daroth\.nuget\packages\system.diagnostics.contracts\4.0.1\lib\netstandard1.0\System.Diagnostics.Contracts.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq\4.1.0\lib\netstandard1.6\System.Linq.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq.expressions\4.1.0\lib\netstandard1.6\System.Linq.Expressions.dll" 
-a "C:\Users\daroth\.nuget\packages\system.numerics.vectors\4.1.1\lib\netstandard1.0\System.Numerics.Vectors.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.objectmodel\4.0.12\lib\netstandard1.3\System.ObjectModel.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit\4.0.1\lib\netstandard1.3\System.Reflection.Emit.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.ilgeneration\4.0.1\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.lightweight\4.0.1\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.typeextensions\4.1.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.numerics\4.0.1\lib\netstandard1.3\System.Runtime.Numerics.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.serialization.primitives\4.1.1\lib\netstandard1.3\System.Runtime.Serialization.Primitives.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.text.regularexpressions\4.1.0\lib\netstandard1.6\System.Text.RegularExpressions.dll" 
-a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.threading\4.0.11\lib\netstandard1.3\System.Threading.dll" 
-a "C:\Users\daroth\Source\Repos\WebApplication19\WebApplication19\obj\Debug\netstandard2.0\WebApplication19.dll"" 
exited with code 1.	
```

When I disable the linker:

```
1>EXEC : error : Object reference not set to an instance of an object.
1>   at Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolver.AssemblyResolutionContext.<ResolveAssemblies>g__GetAssemblyReferences|13_1(AssemblyEntry current) in /_/src/Microsoft.AspNetCore.Blazor.Build/Core/RuntimeDependenciesResolver.cs:line 103
1>   at Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolver.AssemblyResolutionContext.<ResolveAssemblies>g__ResolveAssembliesCore|13_0(<>c__DisplayClass13_0& ) in /_/src/Microsoft.AspNetCore.Blazor.Build/Core/RuntimeDependenciesResolver.cs:line 91
1>   at Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolver.AssemblyResolutionContext.ResolveAssemblies() in /_/src/Microsoft.AspNetCore.Blazor.Build/Core/RuntimeDependenciesResolver.cs:line 82
1>   at Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolver.ResolveRuntimeDependenciesCore(String entryPoint, String[] applicationDependencies, String[] monoBclDirectories) in /_/src/Microsoft.AspNetCore.Blazor.Build/Core/RuntimeDependenciesResolver.cs:line 46
1>   at Microsoft.AspNetCore.Blazor.Build.Cli.Commands.ResolveRuntimeDependenciesCommand.<>c__DisplayClass0_0.<Command>b__0() in /_/src/Microsoft.AspNetCore.Blazor.Build/Cli/Commands/ResolveRuntimeDependenciesCommand.cs:line 44
1>C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\targets\Blazor.MonoRuntime.targets(538,5): error MSB3073: The command "dotnet "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" resolve-dependencies "C:\Users\daroth\Source\Repos\WebApplication19\WebApplication19\obj\Debug\netstandard2.0\WebApplication19.dll" --references "C:\Users\daroth\Source\Repos\WebApplication19\WebApplication19\obj\Debug\netstandard2.0\blazor\resolve-dependencies.txt" --base-class-library "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\targets\../tools/mono/bcl/" --base-class-library "C:\Users\daroth\.nuget\packages\microsoft.aspnetcore.blazor.build\0.6.0\targets\../tools/mono/bcl/Facades/" --output "C:\Users\daroth\Source\Repos\WebApplication19\WebApplication19\obj\Debug\netstandard2.0\blazor\resolved.assemblies.txt"" exited with code 1.

```

**Comment by danroth27** [comment]
Looks similar to #1504
