### ISSUE TITLE
input type="number" - Error: System.FormatException

### ISSUE THREAD

**Issue by cores-system** [aspnet/Blazor#1556]
Hello, using the `type="number"` parameter I cannot use `double` in `bind`.

**TestPage.cshtml**
```
@page "/testpage"

@functions {
    protected double sum { get; set; }
}

<input type="number" bind="@sum" />
```

When I enter field `4.1` or `4,1`, I get an error.
```
Uncaught (in promise) Error: System.FormatException: Input string was not in a correct format.
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)

   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
    at endInvokeDotNetFromJS (http://localhost:57231/_framework/blazor.server.js:23:48593)
    at http://localhost:57231/_framework/blazor.server.js:23:48162
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:57231/_framework/blazor.server.js:23:48131)
    at http://localhost:57231/_framework/blazor.server.js:16:11652
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:57231/_framework/blazor.server.js:16:11623)
    at e.processIncomingData (http://localhost:57231/_framework/blazor.server.js:16:10229)
    at e.connection.onreceive (http://localhost:57231/_framework/blazor.server.js:16:7298)
    at WebSocket.i.onmessage (http://localhost:57231/_framework/blazor.server.js:16:20346)
endInvokeDotNetFromJS @ blazor.server.js:23
(anonymous) @ blazor.server.js:23
beginInvokeJSFromDotNet @ blazor.server.js:23
(anonymous) @ blazor.server.js:16
e.invokeClientMethod @ blazor.server.js:16
e.processIncomingData @ blazor.server.js:16
connection.onreceive @ blazor.server.js:16
i.onmessage @ blazor.server.js:16
```

Although the `type="number"` specification itself allows floating point numbers.

**Blazor server side**: 0.6

**Comment by devmarc70** [comment]
Could you please provide more details? 
I've checked your scenario locally, works as expected. Link provided by @Suchiman 
https://github.com/aspnet/Blazor/blob/10bdf5b0adc26d781cb54a5764accf11274df2e1/src/Microsoft.AspNetCore.Blazor/Components/BindMethods.cs#L117

**Comment by cores-system** [comment]
@devmarc70, 
http://dt-byte.ru/fa670beb.png

```
dotnet --version
2.1.403
```

**Comment by cores-system** [comment]
@devmarc70, It is worth noting that if I publish in azure, then everything works, but if I use `dotnet Blazor_1556.Server.dll`, I get an error above.

**Comment by cores-system** [comment]
The same example works on Blazor Webassembly

**Comment by cores-system** [comment]
An error occurs in this method.
https://github.com/aspnet/Blazor/blob/10bdf5b0adc26d781cb54a5764accf11274df2e1/src/Microsoft.AspNetCore.Blazor/Components/BindMethods.cs#L117

When using `<input type="number" bind="@sum" />`, there will always be an error
```cs
public static Action<UIEventArgs> SetValueHandler(Action<double> setter, double existingValue)
{
   return _ =>
      {
         var val = (string)((UIChangeEventArgs)_).Value;  // res: 4.1   <=  The value is always with a dot.
         var sum = double.Parse(val);                     // System.FormatException
         setter(sum);                                     // Not called
      };
}
```

**Comment by cores-system** [comment]
If it is important
```
Information: Normalizing '_blazor' to 'http://localhost:5000/_blazor'.
blazor.server.js:2647 Information: WebSocket connected to ws://localhost:5000/_blazor?id=RDr87LjdHUSF1Co33d5UdQ
blazor.server.js:2647 Information: Using HubProtocol 'messagepack'.
```

**Comment by cores-system** [comment]
If it is important
```
Information: Normalizing '_blazor' to 'http://localhost:5000/_blazor'.
blazor.server.js:2647 Information: WebSocket connected to ws://localhost:5000/_blazor?id=RDr87LjdHUSF1Co33d5UdQ
blazor.server.js:2647 Information: Using HubProtocol 'messagepack'.
```

**Comment by cores-system** [comment]
@danroth27 @SteveSandersonMS There is a chance to fix it in Blazor 0.7 ?
