### ISSUE TITLE
Server side blazor Microsoft.JSInterop/SignalR exception when passing large strings 

### ISSUE THREAD

**Issue by Kaffeegangster** [aspnet/Blazor#1614]
passing or returning a string>32k  with Microsoft.JSInterop throws an exception and closes SignalR connection. Do i need to implement some kind of argument chunking ? Is the blazor serialisation buffersize configurable?

Microsoft.AspNetCore.SignalR.HubConnectionHandler:Error: Error when processing requests.

System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_BackpressureDeadlock()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 11613.7288ms 101

**Comment by danroth27** [comment]
You're hitting the [default buffer size limit in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.1#buffer-management). The error message isn't great, but there is an [issue](https://github.com/aspnet/SignalR/issues/2486) to address that. If you want to increase the buffer size you can do that by replacing the call to `app.UseServerSideBlazor<App.Startup>()` with:

```
            app.UseSignalR(route => route.MapHub<BlazorHub>(BlazorHub.DefaultPath, o =>
            {
                o.ApplicationMaxBufferSize = 131072; // larger size
                o.TransportMaxBufferSize = 131072; // larger size
            }));
            app.UseBlazor<App.Startup>();
```

**Comment by Kaffeegangster** [comment]
thank you!
