### ISSUE TITLE
Server Side System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by cyberjaws** [aspnet/Blazor#1762]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AssignEventHandlerId(RenderTreeFrame& frame)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForAttributeFrame(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendAttributeDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitSynchronizationContext.ExecuteBackground(WorkItem item)
Exception thrown: 'MessagePack.Internal.MessagePackDynamicObjectResolverException' in MessagePack.dll
Exception thrown: 'System.TypeInitializationException' in MessagePack.dll
Exception thrown: 'System.TypeInitializationException' in MessagePack.dll
Exception thrown: 'System.TypeInitializationException' in MessagePack.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.AspNetCore.SignalR.Protocols.MessagePack.dll
Exception thrown: 'MessagePack.Internal.MessagePackDynamicObjectResolverException' in MessagePack.dll
Exception thrown: 'System.IndexOutOfRangeException' in System.Private.CoreLib.dll
Exception thrown: 'System.IndexOutOfRangeException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Blazor.Server.BlazorHub:Warning: Unhandled Server-Side exception

**Comment by AndreasTruetschel** [comment]
Are `ClientState.ArrayOfThings.Length` in the for loop and `ArrayOfThings[i]` pointing to the same array, or is this just a typo?
How do you call the `LoadSomeStuffAsync` method?  

To be sure to access the exactly same array instance when requesting the array length and getting the element at the respective index, you could copy the array reference to a new variable before the loop and access the array only through this variable. You have to ensure not to modify the content of the array to be on the safe side regarding threading issues here.

**Comment by cyberjaws** [comment]
Thanks for the consult. 

I will try the following:
```
@if (ClientState.ArrayOfThings.Length > 0)
            {
                var things= ArrayOfThings;
                @for(int index = 0;index < things.Length;index++)
                ...
```

Is there a better way to declare the array inline before the loop (in this case, without the @if statement)?

**Comment by cyberjaws** [comment]
It was my understanding that the await would get marshalled back, however that is not a valid assumption. No worries!
Keep up the good work everyone, can't wait to get this into production. This is a game changer.

**Comment by AndreasTruetschel** [comment]
> Is there a better way to declare the array inline before the loop (in this case, without the @if statement)?  

You can define a C# scope just before the for loop like:
```

@{
   var things = ArrayOfThings;
}
@for(int index = 0; index < things .Length; index++)
{ }
```

> Is there a way to marshall the result of the async call back to the "UI thread" (Is there such a thing in this context)?

To may understanding, there is actually just a single thread running your code (if client side blazor is used) because wasm cannot handle multithreading as of the current version.  
There is no `SynchronizationContext` installed by default, so there is no UI-thread queue, the continuation can be scheduled to.
This is also true for the server side version, where any thread pool thread may process the continuation.  
@SteveSandersonMS Is this correct?
