### ISSUE TITLE
Error installing Microsoft.VisualStudio.BlazorExtension VSIX 

### ISSUE THREAD

**Issue by dlr1** [aspnet/Blazor#328]
I have VS2017 community preview and when I tried to install Microsoft.VisualStudio.BlazorExtension.VSIX,.
I get the following even after installing I installed Razor Language services VSIX
Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.RazorExtension (Razor Language Services)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ExtensionRequiresAdditionalOperationForInstall(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, InstallFlags flags, Boolean& performExtensionUpdate)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by rynowak** [comment]
Do you have VS 2015 15.7-preview1 with the Web Workload?

If that's the case could you please provide the log file (should be linked from the error dialog).

> I get the following even after installing I installed Razor Language services VSIX

This should be included by the Web Workload, you don't need to do any extra steps to install the Razor tools

**Comment by dlr1** [comment]
Here is the log file.
[VSIXInstaller_0ed3da71-55a0-4572-a1c0-1babcdcec624.log](https://github.com/aspnet/Blazor/files/1839686/VSIXInstaller_0ed3da71-55a0-4572-a1c0-1babcdcec624.log)

**Comment by rynowak** [comment]
The logs definitely don't show the Razor extension as present. Can you check whether or not the Razor extension is present at:
```
C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\RazorLanguageServices\
```

Just to triple-check, I'm talking about the "ASP.NET and Web Development" workload, seen here:
![image](https://user-images.githubusercontent.com/1430011/37806272-647d26b6-2dfc-11e8-859d-3b6e04a0282e.png)

You can see this from clicking `Modify` on the Visual Studio Installer

**Comment by dlr1** [comment]
I don't see the Razor extension in the directory you mentioned. Here is what I have installed in VS
![capture](https://user-images.githubusercontent.com/7832757/37807855-78de1f64-2e3f-11e8-9136-a33256b03355.PNG)

**Comment by rynowak** [comment]
If you went to the VS gallery and installed [this](https://marketplace.visualstudio.com/items?itemName=ms-madsk.RazorLanguageServices) I think you will have to repair. That extension is for an ancient version of VS and will break things. 

You should definitely see the Razor extension at `C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\RazorLanguageServices\`

**Comment by dlr1** [comment]
It says 
This extension is already installed to all applicable products.
Let me repair and see

**Comment by rynowak** [comment]
Yes, and to clarify, after repair you should be able to install the Blazor extension. You **SHOULD NOT** need to install anything extra for Razor.

**Comment by dlr1** [comment]
Thankyou. After Repairing VS. install of Blazor extension worked.

**Comment by rynowak** [comment]
Great!
