### ISSUE TITLE
Can Microsoft.Extensions.Logging be used in Blazor?

### ISSUE THREAD

**Issue by DNF-SaS** [aspnet/Blazor#700]
Unfortunately, no luck using
`services.AddLogging(loggingBuilder => loggingBuilder.AddConsole());`
and
`ILogger<xxx> logger`
and the "2.1.0-preview2-final"-Packages of Microsoft.Extensions.Logging.

Is there anything special to consider?

**Comment by danroth27** [comment]
@Kumpera

When I try to use Microsoft.Extensions.Logging in Blazor I get the following exception. Possibly related to https://github.com/aspnet/Logging/issues/560:

```
Error: System.ExecutionEngineException: MonoError reused after mono_error_cleanup
  at System.Threading.Thread.StartInternal (System.Security.Principal.IPrincipal principal, System.Threading.StackCrawlMark& stackMark) <0x1bc70d0 + 0x00018> in <0c80fbc440f3492c95ea0f7fb5d8060d>:0 
  at System.Threading.Thread.Start (System.Threading.StackCrawlMark& stackMark) <0x1bc6ec0 + 0x00052> in <0c80fbc440f3492c95ea0f7fb5d8060d>:0 
  at System.Threading.Thread.Start () <0x1bc6d08 + 0x00012> in <0c80fbc440f3492c95ea0f7fb5d8060d>:0 
  at Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor..ctor () <0x1bac338 + 0x0005c> in <2522672923e64ec787b204062488b573>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider..ctor (Microsoft.Extensions.Options.IOptionsMonitor`1[TOptions] options) <0x1bab558 + 0x00018> in <2522672923e64ec787b204062488b573>:0 
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) <0x18fc328 + 0x00030> in <0c80fbc440f3492c95ea0f7fb5d8060d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b6ac80 + 0x000d8> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00126> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b66dd0 + 0x00070> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b669c8 + 0x00024> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00162> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable (Microsoft.Extensions.DependencyInjection.ServiceLookup.IEnumerableCallSite enumerableCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b6af78 + 0x00058> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00108> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b6ac80 + 0x00056> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00126> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b66dd0 + 0x00070> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b669c8 + 0x00024> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00162> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b6ac80 + 0x00056> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00126> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b66dd0 + 0x00070> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b669c8 + 0x00024> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00162> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1a93568 + 0x0001c> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider+<>c__DisplayClass22_0.<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1a933a8 + 0x00064> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) <0x1a85828 + 0x0004a> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Services.BrowserServiceProvider.GetService (System.Type serviceType) <0x1a85470 + 0x00018> in <08ceae4b872f4f8d8ccefc410a9a8971>:0 
  at Microsoft.AspNetCore.Blazor.Components.ComponentFactory+<>c__DisplayClass6_0.<CreateInitializer>b__2 (Microsoft.AspNetCore.Blazor.Components.IComponent instance) <0x1a4a210 + 0x0005c> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.ComponentFactory.PerformPropertyInjection (Microsoft.AspNetCore.Blazor.Components.IComponent instance) <0x1a252e8 + 0x0006a> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.ComponentFactory.InstantiateComponent (System.Type componentType) <0x1a22c68 + 0x00070> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.InstantiateComponent (System.Type componentType) <0x1a22a98 + 0x00018> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.InstantiateChildComponentOnFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeFrame& frame) <0x1a63b68 + 0x0005c> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1a63a20 + 0x00052> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1a638c8 + 0x00074> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InsertNewFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 newFrameIndex) <0x1a63358 + 0x000b4> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 oldStartIndex, System.Int32 oldEndIndexExcl, System.Int32 newStartIndex, System.Int32 newEndIndexExcl) <0x1a60e80 + 0x0025e> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff (Microsoft.AspNetCore.Blazor.Rendering.Renderer renderer, Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange`1[T] oldTree, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange`1[T] newTree) <0x1a608e0 + 0x000a2> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1a59ad8 + 0x000b4> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderQueueEntry renderQueueEntry) <0x1a59680 + 0x00040> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue () <0x1a56ca8 + 0x00048> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue (System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1a55d20 + 0x00068> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.RenderHandle.Render (Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1a55a08 + 0x00036> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.StateHasChanged () <0x1a55910 + 0x00048> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x1a51998 + 0x000b2> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent (System.Type componentType, System.String domElementSelector) <0x1a22970 + 0x0005e> in <08ceae4b872f4f8d8ccefc410a9a8971>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent[TComponent] (System.String domElementSelector) <0x1a22660 + 0x00020> in <08ceae4b872f4f8d8ccefc410a9a8971>:0 
  at WebApplication9.Client.Program.Main (System.String[] args) <0x1863768 + 0x00036> in <649752550d524888a728a3f71d62618c>:0 
  at System.Threading.Thread.StartInternal (System.Security.Principal.IPrincipal principal, System.Threading.StackCrawlMark& stackMark) <0x1bc70d0 + 0x00018> in <0c80fbc440f3492c95ea0f7fb5d8060d>:0 
  at System.Threading.Thread.Start (System.Threading.StackCrawlMark& stackMark) <0x1bc6ec0 + 0x00052> in <0c80fbc440f3492c95ea0f7fb5d8060d>:0 
  at System.Threading.Thread.Start () <0x1bc6d08 + 0x00012> in <0c80fbc440f3492c95ea0f7fb5d8060d>:0 
  at Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor..ctor () <0x1bac338 + 0x0005c> in <2522672923e64ec787b204062488b573>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider..ctor (Microsoft.Extensions.Options.IOptionsMonitor`1[TOptions] options) <0x1bab558 + 0x00018> in <2522672923e64ec787b204062488b573>:0 
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) <0x18fc328 + 0x00030> in <0c80fbc440f3492c95ea0f7fb5d8060d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b6ac80 + 0x000d8> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00126> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b66dd0 + 0x00070> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b669c8 + 0x00024> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00162> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable (Microsoft.Extensions.DependencyInjection.ServiceLookup.IEnumerableCallSite enumerableCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b6af78 + 0x00058> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00108> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b6ac80 + 0x00056> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00126> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b66dd0 + 0x00070> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b669c8 + 0x00024> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00162> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b6ac80 + 0x00056> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00126> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b66dd0 + 0x00070> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1b669c8 + 0x00024> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) <0x1a97328 + 0x00162> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1a93568 + 0x0001c> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider+<>c__DisplayClass22_0.<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceProvider provider) <0x1a933a8 + 0x00064> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) <0x1a85828 + 0x0004a> in <11a24722b687485fb7c0a5da34b5b018>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Services.BrowserServiceProvider.GetService (System.Type serviceType) <0x1a85470 + 0x00018> in <08ceae4b872f4f8d8ccefc410a9a8971>:0 
  at Microsoft.AspNetCore.Blazor.Components.ComponentFactory+<>c__DisplayClass6_0.<CreateInitializer>b__2 (Microsoft.AspNetCore.Blazor.Components.IComponent instance) <0x1a4a210 + 0x0005c> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.ComponentFactory.PerformPropertyInjection (Microsoft.AspNetCore.Blazor.Components.IComponent instance) <0x1a252e8 + 0x0006a> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.ComponentFactory.InstantiateComponent (System.Type componentType) <0x1a22c68 + 0x00070> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.InstantiateComponent (System.Type componentType) <0x1a22a98 + 0x00018> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.InstantiateChildComponentOnFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeFrame& frame) <0x1a63b68 + 0x0005c> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1a63a20 + 0x00052> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1a638c8 + 0x00074> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.InsertNewFrame (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 newFrameIndex) <0x1a63358 + 0x000b4> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange (Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 oldStartIndex, System.Int32 oldEndIndexExcl, System.Int32 newStartIndex, System.Int32 newEndIndexExcl) <0x1a60e80 + 0x0025e> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff (Microsoft.AspNetCore.Blazor.Rendering.Renderer renderer, Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange`1[T] oldTree, Microsoft.AspNetCore.Blazor.RenderTree.ArrayRange`1[T] newTree) <0x1a608e0 + 0x000a2> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1a59ad8 + 0x000b4> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Blazor.Rendering.RenderQueueEntry renderQueueEntry) <0x1a59680 + 0x00040> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue () <0x1a56ca8 + 0x00048> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue (System.Int32 componentId, Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1a55d20 + 0x00068> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.RenderHandle.Render (Microsoft.AspNetCore.Blazor.RenderFragment renderFragment) <0x1a55a08 + 0x00036> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.StateHasChanged () <0x1a55910 + 0x00048> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Components.BlazorComponent.SetParameters (Microsoft.AspNetCore.Blazor.Components.ParameterCollection parameters) <0x1a51998 + 0x000b2> in <8a8022566b074cca8a70e10050945cdd>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent (System.Type componentType, System.String domElementSelector) <0x1a22970 + 0x0005e> in <08ceae4b872f4f8d8ccefc410a9a8971>:0 
  at Microsoft.AspNetCore.Blazor.Browser.Rendering.BrowserRenderer.AddComponent[TComponent] (System.String domElementSelector) <0x1a22660 + 0x00020> in <08ceae4b872f4f8d8ccefc410a9a8971>:0 
  at WebApplication9.Client.Program.Main (System.String[] args) <0x1863768 + 0x00036> in <649752550d524888a728a3f71d62618c>:0 
    at Object.callMethod (http://localhost:53632/_framework/blazor.js:435:23)
    at Object.callEntryPoint (http://localhost:53632/_framework/blazor.js:417:30)
    at http://localhost:53632/_framework/blazor.js:356:44
    at step (http://localhost:53632/_framework/blazor.js:309:23)
    at Object.next (http://localhost:53632/_framework/blazor.js:290:53)
    at fulfilled (http://localhost:53632/_framework/blazor.js:281:58)
```

**Comment by rynowak** [comment]
What if you use it without the console logger? Our console logger offloads the actual logging work to a background thread.  In theory we might need to write a different logger provider to make it work in the browser.

**Comment by kumpera** [comment]
@danroth27 this is odd, I'll take a look why we're not failing nicely.

Regardless, even if I fix the crash, this won't work because it's trying to create a thread, which is not supported.

**Comment by attilah** [comment]
@DNF-SaS don't know if you saw, but @galvesribeiro and me released a logging extension for Blazor: https://github.com/BlazorExtensions/Logging

**Comment by galvesribeiro** [comment]
Just for reference, that extension uses Microsoft.Extensions.Logging

**Comment by danroth27** [comment]
Cool, thx!
